//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARRIENDO
    {
        public int ID_ARRIENDO { get; set; }
        public int ID_PROPIEDAD { get; set; }
        public int ID_INQUILINO { get; set; }
        public int ID_EMPLEADO { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public Nullable<System.DateTime> FECHA_FIN { get; set; }
        public decimal CANON_MENSUAL { get; set; }
        public Nullable<decimal> DEPOSITO { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual PROPIEDADE PROPIEDADE { get; set; }
    }
}
