//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class INMOBILIARIAEntities1 : DbContext
    {
        public INMOBILIARIAEntities1()
            : base("name=INMOBILIARIAEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ARRIENDO> ARRIENDOS { get; set; }
        public virtual DbSet<CIUDADE> CIUDADES { get; set; }
        public virtual DbSet<CLIENTE> CLIENTES { get; set; }
        public virtual DbSet<CONSIGNACIONE> CONSIGNACIONES { get; set; }
        public virtual DbSet<DETALLES_ORDEN> DETALLES_ORDEN { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADOS { get; set; }
        public virtual DbSet<ESTADOS_PROPIEDAD> ESTADOS_PROPIEDAD { get; set; }
        public virtual DbSet<IMAGENES_PROPIEDAD> IMAGENES_PROPIEDAD { get; set; }
        public virtual DbSet<ORDENES_COMPRA> ORDENES_COMPRA { get; set; }
        public virtual DbSet<PERFIL> PERFILs { get; set; }
        public virtual DbSet<PROPIEDADE> PROPIEDADES { get; set; }
        public virtual DbSet<PROPIEDADES_MODELO> PROPIEDADES_MODELO { get; set; }
        public virtual DbSet<PROPIETARIO> PROPIETARIOS { get; set; }
        public virtual DbSet<PROVEEDORE> PROVEEDORES { get; set; }
        public virtual DbSet<PROYECTO> PROYECTOS { get; set; }
        public virtual DbSet<SEDE> SEDES { get; set; }
        public virtual DbSet<TIPOS_PROPIEDAD> TIPOS_PROPIEDAD { get; set; }
        public virtual DbSet<TIPOS_PROVEEDOR> TIPOS_PROVEEDOR { get; set; }
        public virtual DbSet<TIPOS_VISITA> TIPOS_VISITA { get; set; }
        public virtual DbSet<USUARIO> USUARIOs { get; set; }
        public virtual DbSet<USUARIO_PERFIL> USUARIO_PERFIL { get; set; }
        public virtual DbSet<VENTA> VENTAS { get; set; }
        public virtual DbSet<VISITA> VISITAS { get; set; }
    }
}
