//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDENES_COMPRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDENES_COMPRA()
        {
            this.DETALLES_ORDEN = new HashSet<DETALLES_ORDEN>();
        }
    
        public int ID_ORDEN { get; set; }
        public int ID_PROVEEDOR { get; set; }
        public int ID_EMPLEADO { get; set; }
        public System.DateTime FECHA_ORDEN { get; set; }
        public decimal TOTAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLES_ORDEN> DETALLES_ORDEN { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual PROVEEDORE PROVEEDORE { get; set; }
    }
}
