//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROPIEDADES_MODELO
    {
        public int ID_PROPIEDAD { get; set; }
        public int ID_PROYECTO { get; set; }
        public Nullable<decimal> COSTO_DECORACION { get; set; }
        public Nullable<System.DateTime> FECHA_DECORACION { get; set; }
    
        public virtual PROPIEDADE PROPIEDADE { get; set; }
        public virtual PROYECTO PROYECTO { get; set; }
    }
}
