//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDORE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROVEEDORE()
        {
            this.ORDENES_COMPRA = new HashSet<ORDENES_COMPRA>();
        }
    
        public int ID_PROVEEDOR { get; set; }
        public string NOMBRE_COMERCIAL { get; set; }
        public string NIT { get; set; }
        public string TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public int ID_TIPO_PROVEEDOR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDENES_COMPRA> ORDENES_COMPRA { get; set; }
        public virtual TIPOS_PROVEEDOR TIPOS_PROVEEDOR { get; set; }
    }
}
