//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROYECTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROYECTO()
        {
            this.PROPIEDADES_MODELO = new HashSet<PROPIEDADES_MODELO>();
        }
    
        public int ID_PROYECTO { get; set; }
        public string NOMBRE { get; set; }
        public int ID_CIUDAD { get; set; }
        public string DIRECCION { get; set; }
        public Nullable<System.DateTime> FECHA_LANZAMIENTO { get; set; }
        public Nullable<System.DateTime> FECHA_ENTREGA_ESTIMADA { get; set; }
        public string DESARROLLADOR { get; set; }
    
        public virtual CIUDADE CIUDADE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROPIEDADES_MODELO> PROPIEDADES_MODELO { get; set; }
    }
}
