//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_PERFIL
    {
        public int ID { get; set; }
        public int ID_USUARIO { get; set; }
        public int ID_PERFIL { get; set; }
        public bool ACTIVO { get; set; }
    
        public virtual PERFIL PERFIL { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
