//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISITA
    {
        public int ID_VISITA { get; set; }
        public int ID_PROPIEDAD { get; set; }
        public int ID_CLIENTE { get; set; }
        public int ID_EMPLEADO { get; set; }
        public int ID_TIPO_VISITA { get; set; }
        public System.DateTime FECHA_HORA { get; set; }
        public string COMENTARIOS { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual PROPIEDADE PROPIEDADE { get; set; }
        public virtual TIPOS_VISITA TIPOS_VISITA { get; set; }
    }
}
